# Default values for htb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

environment: machines
replicaCount:
    kali: 1

namespace:
  create: true
  env: false

ingress:
  create: true
  domain: "example.com"

volumes:
  pvc:
    - name: htb-st
      claim: htb-cl
      path: /home/kali/storage
      target: kali

containers:
  - name: kali
    image:
      name: oonray/kali
      version: latest
    priveleged: true
    pull: Always
    user: 1000
    ports:
      - name: ssh
        port: 22
        entrypoints:
          - ssh
        tcp: true
      - name: http
        port: 8000
        entrypoints:
          - web
          - websecure
        tcp: false
      - name: proxy
        port: 8080
        entrypoints:
          - web
          - websecure
        tcp: false
        protocol: http
      - name: https
        port: 8443
        entrypoints:
          - websecure
        tcp: false
    volumes:
      - path: /home/kali/storage
        name: htb-st
  - name: vpn
    image:
      name: oonray/vpn
      version: latest
    priveleged: true
    pull: Always
    ports:
      - name: socks
        port: 1080
        entrypoints:
          - socks
        tcp: true
    volumes:
      - path: /opt/conf/vpn/vpn.ovpn
        name: vpn-config
        sub: vpn.ovpn
      - path: /etc/danted/danted.conf
        name: vpn-config
        sub: danted.conf

forward: 1

vpnFile: --set-file vpnFile=vpn.ovpn
config:
  dante:
    logoutput: stdout
    user:
      priveleged: root
      unpriveleged: nobody
    network:
      socks:
        method: none
        from: 0.0.0.0/0
        to: 0.0.0.0/0
      client:
        method: none
        from: 0.0.0.0/0
        to: 0.0.0.0/0
      internal:
        isNet: true
        interface:
        address: 0.0.0.0
        port: 1080
      external:
        isNet: false
        interface: eth0
        address:
