{{- define "containers" }}
containers:
{{- range $cnt := . }}
{{- include "container" $cnt | trim | nindent 2 -}}
{{- end }}
{{- end }}
{{- define "container" }}
- name: {{ .name | quote }}
  image: {{ printf "%s:%s" .image.name .image.version | quote }}
  {{- if hasKey . "tty" }}
  tty: {{ .tty }}
  {{- end }}
  {{- if hasKey . "stdin" }}
  tty: {{ .tty }}
  {{- end }}
  {{- if hasKey . "command" }}
  command: ["/usr/bin/zsh"]
    {{- if hasKey .command "args" }}
  args: ["-c",{{ .command | quote}}
    {{- else }}
  args: ["-c","sleep infinity"]
    {{- end }}
  {{- end }}
  imagePullPolicy: {{ .pull }}
  securityContext:
  {{- if hasKey . "user" }}
    runAsUser: {{ .user }}
  {{- end }}
  {{- if hasKey . "priveleged" }}
    privileged: {{ .priveleged }}
  {{- end }}
  ports:
    {{- range $port := .ports }}
    {{- include "container.port.tcp" $port | trim | nindent 4 }}
    {{- end }}
  volumeMounts:
    {{- range $pvc := .volumes }}
        {{- include "container.volume" $pvc | trim | nindent 4 }}
    {{- end }}
{{- end }}
{{- define "container.port.tcp" }}
- containerPort: {{ .port }}
  name: {{ .name }}
  protocol: TCP
{{- end }}
{{- define "container.port.udp" }}
- containerPort: {{ .port }}
  name: {{ .name }}
  protocol: UDP
{{- end }}
{{- define "container.volume" }}
- mountPath: {{ .path }}
  name: {{ .name }}
  {{- if hasKey . "sub" }}
  subPath: {{ .sub }}
  {{- end }}
{{- end }}
