{{- define "deploy" }}
{{- include "resource" (list . "Deployment" ) | trim }}
spec:
  selector:
    matchLabels:
{{- include "labels" . | trim | nindent 8 }}
  template:
    metadata:
      labels:
{{- include "labels" . | trim | nindent 10 }}
{{- end }}
{{- define "deploy.dns" }}
{{- if hasKey .Values "dnsConfig" }}
dnsConfig:
{{- toYaml .Values.dnsConfig | trim | nindent 4 }}
    {{- end }}
{{- end }}
