{{ define "ingress.traefik" }}
{{- if .port.tcp }}
{{ include "resource" (list . "IngressRouteTCP") | trim }}
{{- else }}
{{ include "resource" (list . "IngressRoute") | trim }}
{{- end }}
spec:
  entryPoints:
    {{- range $e := .port.entrypoints }}
    - {{ $e }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ printf "Host(`%s.%s.%s`)" .port.name .env.Values.environment .env.Values.ingress.domain }}
      services:
          - name: "{{ .port.name }}-service-{{ .env.Values.environment }}"
            port: {{ .port.port }}
{{- include "namespace" .env | trim | nindent 12 }}
{{ end }}


