{{ define "namespace" }}
{{- if hasKey .Values.namespace "name" }}
{{- include "resource.named" (list . "Namespace" .Values.namespace.name ) | trim }}
{{- else }}
{{- include "resource" (list . "Namespace" ) | trim }}
{{- end }}
{{- end }}

{{ define "namespace.tag" }}
{{- if hasKey .Values.namespace "name" }}
    {{- if .Values.namespace.env }}
namespace: "{{ .Values.namespace.name }}-{{ .Values.environment }}"
    {{- else }}
namespace: "{{ .Values.namespace.name }}"
    {{- end }}
{{- else }}
    {{- if .Values.namespace.env }}
namespace: "{{ .Chart.Name }}-{{ .Values.environment }}"
    {{- else }}
namespace: "{{ .Chart.Name }}"
    {{- end }}
{{- end }}
{{ end }}
