{{- define "resource" -}}
apiVersion: apps/v1
kind: {{ index . 1 }}
metadata:
{{- include "resource.metadata" (index . 0) | nindent 2 -}}
{{- end }}
{{- define "resource.named" -}}
{{- $env := (index . 0) -}}
{{- $kind := (index . 1) -}}
{{- $name := (index . 2) -}}
{{- if (eq $kind "Service") }}
    {{- if $env.Values.namespace.env }}
{{- $name = (printf "%s-%s-%s" $env.Chart.Name $name $env.Values.environment) -}}
    {{- else }}
{{- $name = (printf "%s-%s" $env.Chart.Name $name) -}}
    {{- end }}
{{- end }}
{{- if (eq $kind "Secret") }}
apiVersion: v1
{{- else }}
apiVersion: apps/v1
{{- end }}
kind: {{ $kind }}
metadata:
{{- include "resource.metadata.named" (list $env $name) | nindent 2 -}}
{{- end }}

{{- define "resource.metadata" -}}
name: "{{ .Chart.Name }}-{{ .Values.environment }}"
{{- include "namespace.tag" . -}}
labels:
{{- include "labels" . | nindent 2 -}}
{{- end -}}

{{ define "resource.metadata.named" }}
{{- $env := (index . 0) }}
name: "{{ index . 1 }}"
{{- include "namespace.tag" $env }}
labels:
{{- include "labels" $env | nindent 2 }}
{{- end }}
