{{ define "resource" }}
{{- $env := (index . 0) }}
{{- $kind := (index . 1) }}
{{- include "resource.version" (list $kind) | trim }}
---
kind: {{ $kind }}
metadata:
{{- include "resource.metadata" $env | trim | nindent 2 }}
{{ end }}

{{ define "resource.named" }}
{{- $env := (index . 0) }}
{{- $kind := (index . 1) }}
{{- $name := (index . 2) }}
{{- $name = (printf "%s-%s-%s" $env.Chart.Name $name $env.Values.environment) }}
{{- include "resource.version" (list $kind) | trim }}
---
kind: {{ $kind }}
metadata:
{{- include "resource.metadata.named" (list $env $name) | trim | nindent 2 }}
{{ end }}

{{ define "resource.metadata" }}
name: "{{ .Chart.Name }}-{{ .Values.environment }}"
{{ include "namespace.tag" . | trim }}
labels:
{{- include "labels" . | trim | nindent 2 }}
{{ end }}

{{ define "resource.version" }}
{{- $kind := (index . 0) }}
{{- if or (eq $kind "Service") (eq $kind "Secret") }}
apiVersion: v1
{{- else }}
apiVersion: apps/v1
{{- end }}
{{ end }}

{{ define "resource.metadata.named" }}
{{- $env := (index . 0) }}
name: "{{ index . 1 }}"
{{ include "namespace.tag" $env | trim }}
labels:
{{- include "labels" $env | trim | nindent 2 }}
{{ end }}
