{{ define "services" }}
{{- range $cnt := .Values.containers }}
    {{- if hasKey $cnt "ports" }}
{{ include "service" (list $ $cnt) }}
    {{- end }}
{{- end }}
{{ end }}

{{ define "service" }}
{{ $cnt := index . 1}}
---
{{- include "resource.named" (list (index . 0) "Service" $cnt.name ) }}
spec:
{{- if hasKey $cnt "service" }}
{{- if hasKey $cnt.service "type" }}
  type: {{ $cnt.service.type }}
{{- end }}
  selector:
    matchLabels:
{{- include "labels" (index . 0) | nindent 6 }}
  ports:
  {{- range $port := $cnt.ports }}
{{- include "service.port.tcp" $port | nindent 4 }}
  {{- end }}
{{- end }}
{{ end }}

{{- define "service.port.tcp" }}
- port: {{ .port }}
  targetPort: {{ .name }}
  protocol: TCP
{{- end }}
{{- define "service.port.udp" }}
- port: {{ .port }}
  targetPort: {{ .name }}
  protocol: TCP
{{- end }}
