{{- define "volumes" }}
volumes:
{{- range $item := (index . 1) }}
    {{- if eq $item.type "secret" }}
{{- include "volume.secret" (list (index $ 0) $item) | trim | nindent 2 }}
    {{- else }}
{{- include "volume.pvc" $item | trim | nindent 2 }}
    {{- end }}
{{- end }}
{{- end }}

{{- define "volume" }}
{{- $vol := index . 1 }}
{{- include "resource.named" (list (index . 0) "PersistentVolumeClaim" $vol.claim ) | trim }}
spec:
  storageClassName: {{ $vol.class }}
  accessModes:
{{ $vol.access | toYaml | trim | nindent 4 }}
  resources:
    requests:
      storage: {{ $vol.size }}
{{- end }}
{{- define "volume.pvc" }}
- name: {{ .name }}
  persistentVolumeClaim:
    claimName: {{ .claim }}
{{- end }}

{{- define "volume.secret" }}
{{- $env := index . 0 }}
{{- $item := index . 1 }}
- name: {{ $item.name }}
  secret:
    secretName: {{ $env.Chart.Name }}-{{ $item.name }}-{{ $env.Values.environment }}
  items:
  {{- $item.items | toYaml | trim | nindent 6 }}
{{- end }}
