{{ define "ingress.traefik" }}
---
apiVersion: "traefik.io/v1"
{{ if .port.tcp }}
kind: "IngressRouteTCP"
{{ else }}
kind: "IngressRoute"
{{ end }}
metadata:
  name: "{{ .port.name }}-ingress-{{ .env.Values.environment }}"
{{- include "namespace.tag" .env | nindent 2 }}
  labels:
{{- include "labels" .env | nindent 4 }}
spec:
  entryPoints:
    {{- range $e := .port.entrypoints }}
    - {{ $e }}
    {{- end }}
  routes:
    - kind: Rule
      match: {{ printf "Host(`%s.%s.%s`)" .port.name .env.Values.environment .env.Values.ingress.domain }}
      services:
          - name: "{{ .port.name }}-service-{{ .env.Values.environment }}"
            port: {{ .port.port }}
{{- include "namespace" .env | nindent 12 }}
{{ end }}
