{{ define "namespace" }}
{{- if hasKey .Values.namespace "name" }}
apiVersion: v1
kind: Namespace
metadata:
    {{- if .Values.namespace.env }}
  name: "{{ .Values.namespace.name }}-{{ .Values.environment }}"
    {{- else }}
  name: "{{ .Values.namespace.name }}"
    {{- end }}
  labels:
{{ include "labels.environment" . | nindent 4 }}
{{- else }}
apiVersion: v1
kind: Namespace
metadata:
   {{- if .Values.namespace.env }}
  name: "{{ .Chart.Name }}-{{ .Values.environment }}"
   {{- else }}
  name: "{{ .Chart.Name }}"
   {{- end }}
  labels:
{{ include "labels.environment" . | nindent 4 }}
{{- end }}
{{- end }}

{{ define "namespace.tag" }}
{{- if hasKey .Values.namespace "name" }}
    {{- if .Values.namespace.env }}
namespace: "{{ .Values.namespace.name }}-{{ .Values.environment }}"
    {{- else }}
namespace: "{{ .Values.namespace.name }}"
    {{- end }}
{{- else }}
    {{- if .Values.namespace.env }}
namespace: "{{ .Chart.Name }}-{{ .Values.environment }}"
    {{- else }}
namespace: "{{ .Chart.Name }}"
    {{- end }}
{{- end }}
{{ end }}
