{{ define "namespace" }}
{{ if (hasKey .Values.namespace "name") }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace.name }}"
  labels:
{{ include "labels.environment" . | nindent 4 }}
{{ else if .Values.namespace.env}}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.environment }}"
  labels:
{{ else if ((hasKey .Values.namespace "name") and .Values.namespace.env) }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.namespace.name }}-{{ .Values.environment }}"
  labels:
{{ include "labels.environment" . | nindent 4 }}
{{ else }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Chart.Name }}"
  labels:
{{ include "labels" . | nindent 4 }}
{{ end }}
{{ end }}

{{ define "namespace.tag" }}
{{ if (hasKey .Values.namespace "name") }}
namespace: "{{ .Values.namespace.name }}"
{{ else if .Values.namespace.env }}
namespace: "{{ .Values.environment }}"
{{ else if ((hasKey .Values.namespace "name") and .Values.namespace.env) }}
namespace: "{{ .Values.namespace.name }}-{{ .Values.environment }}"
{{ else }}
namespace: "{{ .Chart.Name }}"
{{ end }}
{{ end }}
