{{ define "resource" }}
apiVersion: apps/v1
kind: {{ index . 1 }}
metadata:
{{- include "metadata" (index . 0) | nindent 2 }}
{{- if eq (index . 1) "Deployment" }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
{{ end }}

{{ define "resource.v1" }}
apiVersion: v1
kind: {{ index . 1 }}
metadata:
{{- include "resource.metadata" (index . 0) | nindent 2 }}
{{- if eq (index . 1) "Deployment" }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
{{ end }}

{{ define "resource.named" }}
apiVersion: apps/v1
kind: {{ index . 1 }}
metadata:
{{- include "resource.metadata.named" (list (index . 0) (index . 2)) | nindent 2 }}
{{- if eq (index . 1) "Deployment" }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
{{ end }}

{{ define "resource.metadata" }}
name: "{{ .Chart.Name }}-{{ .Values.environment }}"
{{- include "namespace.tag" . }}
labels:
{{- include "labels" . | nindent 2 }}
{{ end }}

{{ define "resource.metadata.named" }}
name: "{{ index . 1 }}"
{{- include "namespace.tag" (index . 0) }}
labels:
{{- include "labels" (index . 0) | nindent 2 }}
{{ end }}
