{{ define "services" }}
{{- range $cnt := .Values.containers }}
{{ include "service" (slice $ $cnt) }}
{{- end }}
{{ end }}

{{ define "service" }}
{{ $env := index . 0}}
{{ $cnt := index . 1}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $env.Chart.Name }}-service-{{ $env.Values.environment }}
{{ include "namespace.tag" $env | nindent 2 }}
  labels:
{{ include "labels" $env | nindent 4 }}
spec:
  selector:
{{ include "labels" $env | nindent 4 }}
  ports:
  {{- range $port := $cnt.ports }}
{{ toYaml $port | nindent 4 }}
  {{- end }}
{{- if hasKey $cnt "service" }}
    {{- if hasKey $cnt.service "type" }}
  type: {{ $cnt.service.type }}
    {{- end }}
{{- end }}
{{ end }}

