name: Publish to HELM

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      username:
          required: true
      password:
          required: true

jobs:
  package-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(yq -r .version ${{ inputs.path }}/Chart.yaml)" >> "$GITHUB_OUTPUT"
          echo "NAME=$(yq -r .name ${{ inputs.path }}/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Package and push helm chart
        run: |
          helm package ${{ inputs.path }}
          helm push ./${{steps.set-variables.outputs.NAME}}-${{ steps.set-variables.outputs.VERSION }}.tgz oci://registry-1.docker.io/oonray
