name: Publish to HELM

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      username:
          required: true
      password:
          required: true

jobs:
  package-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Package and push helm chart
        run: |
          helm package .
          helm push ./*.tgz oci://registry-1.docker.io/oonray
