name: Docker helm chart templates

on:
  workflow_dispatch:
  push:
    paths:
      - '*'
      - '**'

jobs:
  package-kali-helm:
    uses: oonray/HelmTemplates/.github/workflows/helm.yml@main
    with:
      name: templates
    secrets:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
